name: ktbthon
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    networks:
      - ktb_network
    ports:
      - "8080:8080" #서버
      - "5005:5005" #디버깅
    restart: always
    env_file:
      - .env
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ktb_network
    env_file:
      - .env
  nginx:
    image: nginx:latest
    networks:
      - ktb_network
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    env_file:
      - .env
networks:
  ktb_network:
    driver: bridge
