server:
  port: 5005

spring:
  data:
    mongodb:
      uri: {mongodb_uri}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  devtools:
  restart: enabled=
    spring.devtools.livereload.enabled=true
    server.port=5005